/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import BDD.CRUDPedidos;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author sebastchan
 */
public class Pedidos extends javax.swing.JPanel {

    /**
     * Creates new form Pedidos
     */
    public Pedidos(ArrayList<String[]> pedido, String perfil) {
        initComponents();
        ImageIcon imagenProducto= new ImageIcon(this.getClass().getResource("/images/user.png"));
        this.imgPedido.setIcon(new ImageIcon(imagenProducto.getImage().
                getScaledInstance(250, 250, Image.SCALE_DEFAULT)));
        setProducto(pedido);
        if(perfil.equals("C")){
            this.jbtnAceptar.setVisible(false);
            this.jbtnRechazar.setVisible(false);
        }else
            this.jbtnSolicitar.setVisible(false);
        this.repaint();
    }
    
    public void setProducto(ArrayList<String[]> pedido){
        this.numPedidoText.setText(pedido.get(0)[0]);
        this.fechaText.setText(pedido.get(0)[1]);
        this.estadoText.setText(pedido.get(0)[2]);
        this.totalText.setText("$" + pedido.get(0)[3]);
        if(pedido.get(0)[4].equals("E") || pedido.get(0)[4].equals("N")){
            this.jbtnSolicitar.setEnabled(false);
            if(pedido.get(0)[4].equals("N"))
                this.jbtnSolicitar.setText("Rechazada");
            else
                this.jbtnSolicitar.setText("En espera");
        }
        String productosDetalles = "";
        for (int i = 1; i < pedido.size(); i++) {
            productosDetalles += "- " + pedido.get(i)[0] + 
                                    ": " + pedido.get(i)[1] + 
                                    ". $" + pedido.get(i)[2] + 
                                    " x " + pedido.get(i)[3] + "<br>";
        }
        this.detalleText.setText("<html><body>" + productosDetalles + "</body></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgPedido = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        fechaText = new javax.swing.JLabel();
        numPedidoLabel = new javax.swing.JLabel();
        numPedidoText = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        estadoText = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        totalText = new javax.swing.JLabel();
        detalleLabel = new javax.swing.JLabel();
        detalleText = new javax.swing.JLabel();
        detalleLabel1 = new javax.swing.JLabel();
        jbtnAceptar = new javax.swing.JButton();
        jbtnRechazar = new javax.swing.JButton();
        jbtnSolicitar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        imgPedido.setForeground(new java.awt.Color(204, 102, 255));

        fechaLabel.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        fechaLabel.setForeground(new java.awt.Color(0, 0, 0));
        fechaLabel.setText("Fecha:");

        fechaText.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        fechaText.setForeground(new java.awt.Color(0, 0, 0));
        fechaText.setText("23/01/2023");

        numPedidoLabel.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        numPedidoLabel.setForeground(new java.awt.Color(0, 0, 0));
        numPedidoLabel.setText("N. Pedido:");

        numPedidoText.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        numPedidoText.setForeground(new java.awt.Color(0, 0, 0));
        numPedidoText.setText("10");

        estadoLabel.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        estadoLabel.setForeground(new java.awt.Color(0, 0, 0));
        estadoLabel.setText("Estado:");

        estadoText.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        estadoText.setForeground(new java.awt.Color(0, 0, 0));
        estadoText.setText("Pagado");

        totalLabel.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(0, 0, 0));
        totalLabel.setText("TOTAL:");

        totalText.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        totalText.setForeground(new java.awt.Color(0, 0, 0));
        totalText.setText("$10");

        detalleLabel.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        detalleLabel.setForeground(new java.awt.Color(0, 0, 0));
        detalleLabel.setText("Detalle:");

        detalleText.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        detalleText.setForeground(new java.awt.Color(0, 0, 0));
        detalleText.setText("<html><body>- Producto 1 <br>- Producto 2<br> - Producto 3<br><br><br><br><br><br> </body></html>");
        detalleText.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        detalleLabel1.setFont(new java.awt.Font("Cantarell", 1, 30)); // NOI18N
        detalleLabel1.setForeground(new java.awt.Color(0, 0, 0));
        detalleLabel1.setText("Subtotal:");

        jbtnAceptar.setBackground(new java.awt.Color(0, 204, 51));
        jbtnAceptar.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jbtnAceptar.setForeground(new java.awt.Color(0, 0, 0));
        jbtnAceptar.setText("Aceptar");
        jbtnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbtnRechazar.setBackground(new java.awt.Color(255, 51, 51));
        jbtnRechazar.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jbtnRechazar.setForeground(new java.awt.Color(0, 0, 0));
        jbtnRechazar.setText("Rechazar");
        jbtnRechazar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRechazarActionPerformed(evt);
            }
        });

        jbtnSolicitar.setBackground(new java.awt.Color(51, 51, 255));
        jbtnSolicitar.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jbtnSolicitar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSolicitar.setText("Solicitar Devolución");
        jbtnSolicitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSolicitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSolicitarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(imgPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnSolicitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnAceptar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(numPedidoLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(numPedidoText, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(estadoLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(estadoText, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(fechaLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fechaText, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(detalleLabel)
                        .addGap(279, 279, 279)
                        .addComponent(detalleLabel1)
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(detalleText, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jbtnRechazar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalText, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numPedidoLabel)
                            .addComponent(numPedidoText))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaLabel)
                            .addComponent(fechaText))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estadoLabel)
                            .addComponent(estadoText)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(imgPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(detalleLabel)
                            .addComponent(detalleLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detalleText, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalLabel)
                            .addComponent(totalText)
                            .addComponent(jbtnAceptar)
                            .addComponent(jbtnRechazar))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnSolicitar)
                        .addGap(32, 32, 32))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSolicitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSolicitarMouseClicked
        CRUDPedidos cp = new CRUDPedidos();
        cp.setSolicitudDevolucion(this.numPedidoText.getText());
        PantallaInicial.pantallaInicial.generarPedidos();
    }//GEN-LAST:event_jbtnSolicitarMouseClicked

    private void jbtnRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRechazarActionPerformed
        CRUDPedidos cp = new CRUDPedidos();
        cp.setDevolucionRechazada(this.numPedidoText.getText());
        PantallaInicial.pantallaInicial.generarPedidos();
    }//GEN-LAST:event_jbtnRechazarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detalleLabel;
    private javax.swing.JLabel detalleLabel1;
    private javax.swing.JLabel detalleText;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JLabel estadoText;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel fechaText;
    private javax.swing.JLabel imgPedido;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JButton jbtnRechazar;
    private javax.swing.JButton jbtnSolicitar;
    private javax.swing.JLabel numPedidoLabel;
    private javax.swing.JLabel numPedidoText;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalText;
    // End of variables declaration//GEN-END:variables
}
